# Generated by Django 5.0.6 on 2024-06-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0003_alter_order_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
    ]
