# Generated by Django 4.2.7 on 2025-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_logo',
            field=models.ImageField(blank=True, null=True, upload_to='backend_api/product/media/category_image'),
        ),
    ]
